[bot]
plugins = []
plugin_dirs = ["plugins"]
rules = []
rule_dirs = ["rules"]
adapters = [
    "iamai.adapter.cqhttp",
    "iamai.adapter.apscheduler",
    "iamai.adapter.dingtalk"        
]

[bot.log]
level = "INFO"
verbose_exception = true

[adapter.cqhttp]
adapter_type = "reverse-ws"
host = "127.0.0.1"
port = 8080
url = "/cqhttp/ws"
show_raw = false

[adapter.dingtalk]
adapter_type = "stream"
host = "127.0.0.1"
port = 8081
url = "/dingtalk"
app_secret = "FnQU_a88xRpmcs3oPNXSgoQgm4TidGduVqKhLHR7_NgF6MLBUUbwYdE6MkOFWZFb"
app_key = "dingo7xu5djthkxpoick"

[adapter.apscheduler]
scheduler_config = { "apscheduler.timezone" = "Asia/Shanghai" }

[plugin.HydroRoll]
uid = ''
rules = []
rule_dirs = ["rules"]