packages:
  - ".github/actions/*"
  - "docs"
  - "cli"
  - "packages/*"
  - "benchmark"
  - "turborepo-tests/*"
  # Intentionally exclude the `npm` `turbo` package from the workspaces.
  - "!packages/turbo"
  - "packages/turbo-tracing-next-plugin/test/with-mongodb-mongoose"
  - "crates/next-dev-tests/test-harness"
  - "crates/next-dev-tests/tests"
  - "crates/*/js"
  - examples
