name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        name: Setup PDM
        with:
          python-version: 3.9
          cache: true

      - name: Install dependencies
        run: pdm install

      - run: pdm publish
        shell: bash