baseURL = 'http://hydroroll.team/'
languageCode = 'zh-cn'
title = 'HydroRoll'
theme = 'coming-soon'

[params]
    logo = "assets/img/logo.webp"
    favicon = "assets/favicon.png"
    title = "HydroRoll " 
    description = "倒数日"
    message = "距离水系公测还有" # default is "COMING SOON" 
    release = "Jul 14, 2024" # release date format: Aug 30, 2023 15:00
    background = "" # default is bg.mp4 in static/

socialIcons = [
    {name = "email", url = "support@hydroroll.team"},   
    {name = "github", url = "https://github.com/HydroRoll-Team"},    
] 