baseURL = 'http://www.hydroroll.team/'
languageCode = 'en-us'
title = 'HydroRoll'
theme = 'coming-soon'


[params]
    title = "HydroRoll 水系" 
    description = "一切为了装13!"
    message = "饼在画了!" # default is "COMING SOON" 
    subtitle = "距离水系公测还有"
    release = "Jul 14, 2024" # release date format: Aug 30, 2023 15:00
    background = "" # default is bg.mp4 in static/

socialIcons = [
    {name = "email", url = "support@hydroroll.team"},          
    {name = "github", url = "https://github.com/HydroRoll-Team/"},    
] 