# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

run:
  timeout: 5m
  modules-download-mode: readonly
  go: 1.17
  skip-dirs:
    - internal/yaml # vendored upstream library
  skip-files:
    - internal/chrometracing/chrometracing.go # vendored upstream library

linters:
  enable:
    - errcheck
    - goimports
    - govet
    - staticcheck
    - revive
    - nakedret

linters-settings:
  nakedret:
    # Aggressively disallow naked returns
    max-func-lines: 3

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
