[package]
name = "get-pc"
version = "0.1.0"
edition = "2021"
description = "Experimentally get your character card through an object-oriented program."
license = "MIT"
documentation = "https://get-pc.hydroroll.team/"
homepage = "https://get-pc.hydroroll.team/"
repository = "https://github.com/HydroRoll-Team/GetPlayerCard"
authors = ["HsiangNianian"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.2", features = ["abi3-py39", "extension-module"] }
clap = { version = "4.0", features = ["derive"] }
rand = "0.8.5"