name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      PDM_PUBLISH_USERNAME: ${{ secrets.PYPI_USERNAME }}
    steps:
      - uses: actions/checkout@v3

      - name: Install pdm
        run: pipx install pdm
        shell: bash
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: "x64"
      - run: pdm install
        shell: bash

      - run: pdm publish
        shell: bash